name: Test GitHub Secrets

on:
  workflow_dispatch  # Allows manual execution

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secrets Visibility
        run: |
          echo "🔹 SSH_USER: ${{ secrets.SSH_USER }}"
          echo "🔹 SSH_HOST: ${{ secrets.SSH_HOST }}"
          echo "🔹 SSH_PRIVATE_KEY Length: $(echo -n "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c) characters"

      - name: Test SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ✅ SSH Connection Successful!"

